import type { Product, Category } from "@/types";

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-streaming",
    name: "Streaming",
    slug: "streaming",
    description: "Plataformas de streaming de video",
    icon: "Tv",
    image_url: null,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-musica",
    name: "Música",
    slug: "musica",
    description: "Plataformas de streaming de música",
    icon: "Music",
    image_url: null,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-gaming",
    name: "Gaming",
    slug: "gaming",
    description: "Videojuegos y créditos de juegos",
    icon: "Gamepad2",
    image_url: null,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-recargas",
    name: "Recargas",
    slug: "recargas",
    description: "Recargas de celular y datos",
    icon: "Smartphone",
    image_url: null,
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-giftcards",
    name: "Gift Cards",
    slug: "gift-cards",
    description: "Tarjetas de regalo digitales",
    icon: "Gift",
    image_url: null,
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-otros",
    name: "Otros Servicios",
    slug: "otros-servicios",
    description: "VPN, software, almacenamiento",
    icon: "Globe",
    image_url: null,
    sort_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod-netflix",
    name: "Netflix Premium",
    slug: "netflix-premium",
    description:
      "Cuenta Netflix Premium con acceso a 4 pantallas simultáneas en calidad Ultra HD. Disfruta de todo el catálogo de películas, series, documentales y contenido exclusivo de Netflix.",
    short_description: "4 pantallas, Ultra HD, catálogo completo",
    price: 5.99,
    compare_at_price: 15.99,
    cost_price: 3.0,
    category_id: "cat-streaming",
    product_type: "profile",
    image_url: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=400&h=300&fit=crop",
    images: [],
    stock: 50,
    is_active: true,
    is_featured: true,
    metadata: {},
    tags: ["streaming", "netflix", "premium"],
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-disney",
    name: "Disney+ Premium",
    slug: "disney-plus-premium",
    description:
      "Accede a todo el contenido de Disney, Pixar, Marvel, Star Wars y National Geographic en calidad 4K HDR.",
    short_description: "Disney, Marvel, Star Wars en 4K HDR",
    price: 4.99,
    compare_at_price: 12.99,
    cost_price: 2.5,
    category_id: "cat-streaming",
    product_type: "profile",
    image_url: "https://images.unsplash.com/photo-1640499900704-b00dd6a1104a?w=400&h=300&fit=crop",
    images: [],
    stock: 35,
    is_active: true,
    is_featured: true,
    metadata: {},
    tags: ["streaming", "disney", "marvel"],
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-hbomax",
    name: "Max (HBO) Premium",
    slug: "max-hbo-premium",
    description: "Disfruta de HBO Max con acceso completo a series exclusivas, películas de estreno y contenido premium.",
    short_description: "Series HBO, películas de estreno",
    price: 4.49,
    compare_at_price: 11.99,
    cost_price: 2.0,
    category_id: "cat-streaming",
    product_type: "profile",
    image_url: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400&h=300&fit=crop",
    images: [],
    stock: 28,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["streaming", "hbo", "max"],
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-prime",
    name: "Amazon Prime Video",
    slug: "amazon-prime-video",
    description: "Cuenta de Amazon Prime Video con acceso a series, películas y contenido exclusivo de Amazon.",
    short_description: "Series y películas exclusivas Amazon",
    price: 3.99,
    compare_at_price: 9.99,
    cost_price: 2.0,
    category_id: "cat-streaming",
    product_type: "full_account",
    image_url: "https://images.unsplash.com/photo-1521967906867-14ec9d64bee8?w=400&h=300&fit=crop",
    images: [],
    stock: 40,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["streaming", "amazon", "prime"],
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-spotify",
    name: "Spotify Premium",
    slug: "spotify-premium",
    description:
      "Escucha millones de canciones sin anuncios, descarga música offline y disfruta de audio en alta calidad.",
    short_description: "Sin anuncios, descarga offline, HQ audio",
    price: 3.99,
    compare_at_price: 9.99,
    cost_price: 2.0,
    category_id: "cat-musica",
    product_type: "membership",
    image_url: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400&h=300&fit=crop",
    images: [],
    stock: 60,
    is_active: true,
    is_featured: true,
    metadata: {},
    tags: ["musica", "spotify", "premium"],
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "prod-applemusic",
    name: "Apple Music",
    slug: "apple-music",
    description: "Accede a más de 100 millones de canciones, audio sin pérdida y Dolby Atmos.",
    short_description: "100M+ canciones, Lossless, Dolby Atmos",
    price: 4.49,
    compare_at_price: 10.99,
    cost_price: 2.5,
    category_id: "cat-musica",
    product_type: "membership",
    image_url: "https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=400&h=300&fit=crop",
    images: [],
    stock: 30,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["musica", "apple", "lossless"],
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "prod-gamepass",
    name: "Xbox Game Pass Ultimate",
    slug: "xbox-game-pass-ultimate",
    description:
      "Accede a cientos de juegos en Xbox, PC y la nube. Incluye Xbox Live Gold, EA Play y más.",
    short_description: "Cientos de juegos, Xbox + PC + Cloud",
    price: 12.99,
    compare_at_price: 17.99,
    cost_price: 8.0,
    category_id: "cat-gaming",
    product_type: "subscription",
    image_url: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400&h=300&fit=crop",
    images: [],
    stock: 25,
    is_active: true,
    is_featured: true,
    metadata: {},
    tags: ["gaming", "xbox", "gamepass"],
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
  },
  {
    id: "prod-robux",
    name: "Robux 800",
    slug: "robux-800",
    description: "800 Robux para Roblox. Personaliza tu avatar, compra accesorios y desbloquea experiencias.",
    short_description: "800 Robux para tu cuenta de Roblox",
    price: 9.99,
    compare_at_price: null,
    cost_price: 7.0,
    category_id: "cat-gaming",
    product_type: "code",
    image_url: "https://images.unsplash.com/photo-1616588589676-62b3d4ff6a90?w=400&h=300&fit=crop",
    images: [],
    stock: 100,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["gaming", "roblox", "robux"],
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
  },
  {
    id: "prod-vbucks",
    name: "V-Bucks 1000",
    slug: "v-bucks-1000",
    description: "1000 V-Bucks para Fortnite. Compra skins, pases de batalla y más.",
    short_description: "1000 V-Bucks para Fortnite",
    price: 8.99,
    compare_at_price: 11.99,
    cost_price: 6.0,
    category_id: "cat-gaming",
    product_type: "code",
    image_url: "https://images.unsplash.com/photo-1589241062272-c0a000072dfa?w=400&h=300&fit=crop",
    images: [],
    stock: 75,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["gaming", "fortnite", "vbucks"],
    sort_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
  },
  {
    id: "prod-recarga50",
    name: "Recarga Telcel $50",
    slug: "recarga-telcel-50",
    description: "Recarga de saldo Telcel por $50 MXN. Se aplica automáticamente a tu número.",
    short_description: "Recarga automática de saldo Telcel",
    price: 5.0,
    compare_at_price: null,
    cost_price: 4.5,
    category_id: "cat-recargas",
    product_type: "recharge",
    image_url: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=300&fit=crop",
    images: [],
    stock: 200,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["recargas", "telcel", "saldo"],
    sort_order: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[3],
  },
  {
    id: "prod-google-play",
    name: "Google Play $25",
    slug: "google-play-25",
    description: "Tarjeta de regalo Google Play de $25 USD. Compra apps, juegos, películas y más.",
    short_description: "Gift card $25 USD Google Play",
    price: 25.0,
    compare_at_price: null,
    cost_price: 22.0,
    category_id: "cat-giftcards",
    product_type: "gift_card",
    image_url: "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=400&h=300&fit=crop",
    images: [],
    stock: 45,
    is_active: true,
    is_featured: true,
    metadata: {},
    tags: ["giftcard", "google", "play"],
    sort_order: 11,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[4],
  },
  {
    id: "prod-nordvpn",
    name: "NordVPN 1 Año",
    slug: "nordvpn-1-year",
    description: "Suscripción de NordVPN por 1 año. Navega de forma segura y privada desde cualquier lugar.",
    short_description: "VPN premium por 1 año completo",
    price: 29.99,
    compare_at_price: 59.99,
    cost_price: 15.0,
    category_id: "cat-otros",
    product_type: "subscription",
    image_url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=300&fit=crop",
    images: [],
    stock: 20,
    is_active: true,
    is_featured: false,
    metadata: {},
    tags: ["vpn", "nordvpn", "seguridad"],
    sort_order: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[5],
  },
];
